### ISSUE TITLE
GUI planned ?

### ISSUE THREAD

**Issue by lapineige** [wanadev/yoga#27]
Hello,

I would like to know if you are planning to implement a Graphical User Interface for that software ?

Thanks

**Comment by flozz** [comment]
Hello,

There is currently no plan for a GUI... at least for Wanadev (we do not need a GUI).

I am thinking about making a GTK GUI for YOGA Image for my own usage but I do not know when I will do this...

**Comment by lapineige** [comment]
That's what I expected. Sad news, but thanks for that piece of information :)

**Comment by lapineige** [comment]
Thanks for your reply. Then finger crossed, I hope you (or someone else) will find the time to do this :)

**Comment by lapineige** [comment]
So now we have the GUI :tada: https://github.com/flozz/yoga-image-optimizer
