### ISSUE TITLE
Multithreading support ?

### ISSUE THREAD

**Issue by lapineige** [wanadev/yoga#28]
Hello,
Any chance that Yoga includes multi-threading in the future ?

Overall performance seems pretty ok for small jpeg images, but for bigger ones it's really slow. One 75MB PNG (50Mpixels) took 30min to be converted, a 1.6MB PNG took 6min (but 33% saved, nice :).

Thanks

**Comment by flozz** [comment]
Hello,

Behind the scene YOGA uses Guetzli for JPEGs and ZopfliPNG for PNGs. As far as I know, those libraries does not support multi-threading, so this will not be supported. :)

**Comment by lapineige** [comment]
That's what I expected. Sad news, but thanks for that piece of information :)

**Comment by lapineige** [comment]
Hello,

For your information, there is a fork that supports multithreading: https://github.com/MrKrzYch00/zopfli
I don't know to what extend it's possible for you to use it, but maybe there's a chance… :)

**Comment by flozz** [comment]
Maby it can be an option but It will need test and there is probably no Python binding for this yet

**Comment by lapineige** [comment]
I'm wiling to test it if there a way :) (that doesn't involve programming)

As for the python binding, I have no idea, maybe @MrKrzYch00 could have some input here ?
