### ISSUE TITLE
High memory usage during image conversion

### ISSUE THREAD

**Issue by lapineige** [wanadev/yoga#29]
Hello,

I did convert a few files and notices a very high memory usage (often about 12 times the size of the original png), and in particular my last test with a 9000x3000 PNG file (44MB) did use more than 20GB of RAM, which seems extreme for such a file…
So I wonder if that's something expected (and if yes, what would be possible to reduce the memory usage ?) or a bug on my side.

Thanks in advance

**Comment by flozz** [comment]
Hello,

I will take a look to check that the Python code inside YOGA do not keep useless copies of the data, but it is known that Guetzli (for JPEG) use a lot of memory, and I do not know if it is the same with Zopfli. I will make some tests.

**Comment by flozz** [comment]
I updated the PNG optimization preset in YOGA v1.0.0, it may be better now :)

**Comment by lapineige** [comment]
That's great !
I did a quick test, using a 3.4MiB png screenshot: it took something like 1m and up to ~100MB of memory, for a resulting file of 3.1MiB.
The old preset took about 8m and up to ~120MB of RAM, for a result file of… 3.1MiB (to be precise: 8.8kB less than with the new preset, -0,3%…).


That new preset is really great ! It makes yoga really usable for daily use with big PNG. Thanks a lot :rocket:


PS: great to see WebP support too !
