### ISSUE TITLE
[Feature request] progression indicator

### ISSUE THREAD

**Issue by lapineige** [wanadev/yoga#30]
Hello,

Because of the very long computation time for a lot of images (#28), a progression indicator (like a progress bar, or just a vague percentage) would be useful to estimate how long the processing will take.
What do you think about such a feature ? Any chance it gets implemented ?

Thank you

**Comment by flozz** [comment]
Hello,

I do not think it will be possible in YOGA as libraries do not give us feedback of the progression of the computation (or I missed the information). 

I started to work on a [GUI](https://twitter.com/flogisoft/status/1363518375893336066) that will allow batch optimizations of images and that will display the progression in the batch.

**Comment by lapineige** [comment]
And are those libraries used only once, with one step (that is a block box with no progression info) ? Or is it divided in a few steps ? If that so, maybe you could display these steps ? (that would at least give some indications)

**Comment by lapineige** [comment]
Nice to see a GUI on the making, that would be a great addition. And it would easy my life when converting multiple images, as it takes a loooot of time, I often miss the end of some compression and loose that precious time without launching a new one 😅

**Comment by flozz** [comment]
> And are those libraries used only once, with one step (that is a block box with no progression info) ? Or is it divided in a few steps ? If that so, maybe you could display these steps ? (that would at least give some indications)

They are black box :

* YOGA open and decode the image (using Pillow)
* Then it resize the image if the resize option was given (also with Pillow)
* Then it gives the data to the library (as an array of RGB pixels for Guetzli or as a PNG encoded image for Zopfli)
* And finally we get back the data from the libraries and write them in a file 

And 99% of the time of this is in Guetzli or Zopfli

**Comment by lapineige** [comment]
Thanks for the explanations.
It seems that those libraries are very powerful in terms of compression, but not that handy to manipulate :sweat_smile:

**Comment by lapineige** [comment]
Version 1.0.0 seems to reduces considerably the compression time (https://github.com/wanadev/yoga/issues/29#issuecomment-828205716), then that feature is not as needed as before.
