### ISSUE TITLE
Need more documentation about how to locally build Yoga for development work

### ISSUE THREAD

**Issue by Krenodeno** [wanadev/yoga#31]
There is no documentation on about how to build yoga and its dependencies.

FYI @flozz

**Comment by Breush** [comment]
What is missing from https://wanadev.github.io/yoga/contributing.html ?

**Comment by flozz** [comment]
@Breush A "howto work on yoga" section is missing, with instructions like 

* How to build for dev:

```
python setup.py build
python yoga/model/assimp_build.py
```
and then how to run for dev:
```
python -m yoga ...
```

:)
