### ISSUE TITLE
Inverted normals on a specific model 

### ISSUE THREAD

**Issue by vincentriche** [wanadev/yoga#32]
I used yoga to convert a fbx (composed of two submeshes) into a glb and the normals of one of submesh are inverted.

There is a screen:
![screen ](https://user-images.githubusercontent.com/10024751/114712296-3b12a200-9d30-11eb-88d6-819cf1c67311.png)

I set Blender in display normals mode. Blue color is normals facing the camera

**Comment by vincentriche** [comment]
I tried to comment the `fix-infacing-normals` in Yoga, and it worked!

BUT, i cloned the repo assimp, checkout the same version we have in yoga, tried to export my object with the `fix-infacing-normals` flag activated, and it worked too.     
Maybe i am not using the parameter correctly ?
`./bin/assimp export original.fbx test.glb --fix-infacing-normals`

**Comment by vincentriche** [comment]
My bad, i was using wrong parameters. i have the same result with assimp and the parameter `-fixn`

**Comment by Breush** [comment]
I guess I had put this flag because some models we had at Wanadev needed it.
Maybe this needs to be active only on option.

**Comment by vincentriche** [comment]
We are exactly doing this right now :)

The PR is on its way !

**Comment by vincentriche** [comment]
https://github.com/wanadev/yoga/pull/33 :D
