### ISSUE TITLE
Fix installation documentation

### ISSUE THREAD

**Issue by flozz** [wanadev/yoga#34]
In the installation doc, the instructions to get the git submodule are missing

**Comment by Popolon** [comment]
I tried to install it on Debian bullseye (for RISC-V ISA) via `pip install yoga`, and it fail with the same error, that o
```
[...]
 [ 61%] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCReaderGen1_2x3.cpp.o
  c++: fatal error: Processus arrêté signal terminated program cc1plus
  compilation terminated.
  make[2]: *** [code/CMakeFiles/assimp.dir/build.make:1720 : code/CMakeFiles/assimp.dir/AssetLib/IFC/IFCReaderGen1_2x3.cpp.o] Erreur 1
  make[1]: *** [CMakeFiles/Makefile2:189 : code/CMakeFiles/assimp.dir/all] Erreur 2
  make: *** [Makefile:149 : all] Erreur 2
  creating build
  creating build/lib.linux-riscv64-3.9
  creating build/lib.linux-riscv64-3.9/yoga
[...]

```

**Comment by flozz** [comment]
I do not think you issue is related to the missing instructions in the doc: the "`fatal error: Processus arrêté signal terminated program cc1plus`" error is probably due to a lack of RAM while compiling :)

**Comment by flozz** [comment]
I close the issue as I deployed the missing doc :)
